name: Gradle Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Read Artifact Version Info
      run: grep 'version' build.gradle
      
    - name: Update Artifact Minor Version
      run:  sed -i "s/micro_version=.*/micro_version=${{github.run_number}}/g" build.gradle
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test bootJar
        gradle-version: 7.6.1
        
    - name: List Build Artifacts
      run: ls build/libs/github-actions-template-*.jar

    - name: create tag
      uses: rickstaa/action-create-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{github.run_number}}
        message: ""

    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        tag_name: ${{github.run_number}}
        
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: "build.gradle"
